- name: Create .ssh directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.ssh"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0700"

- name: "Set authorized keys for {{ ansible_user }}"
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ item }}"
    state: present
    exclusive: false
  loop: "{{ ssh_keys }}"
