- name: Ubuntu > blacklist ipv6 in modprobe
  ansible.builtin.lineinfile:
    dest: /etc/modprobe.d/blacklist.conf
    line: 'blacklist ipv6'
    mode: '0644'
    create: true
  when: ansible_os_family == 'Debian'

- name: Ensure GRUB_CMDLINE_LINUX_DEFAULT contains "quiet splash ipv6.disable=1"
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash ipv6.disable=1"'
  notify:
    - Reboot server

- name: Ensure GRUB_CMDLINE_LINUX contains "ipv6.disable=1"
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="ipv6.disable=1"'
  notify:
    - Reboot server

- name: Update grub
  ansible.builtin.command:
    cmd: update-grub