version: 2

enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: 0 2 * * *
      timezone: "America/New_York"
    commit-message:
      prefix: "chore(deps)"
    cooldown:
      default-days: 7
  
  - package-ecosystem: "uv"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: 0 2 * * *
      timezone: "America/New_York"
    commit-message:
      prefix: "chore(uv.lock)"
    cooldown:
      default-days: 7
      
  - package-ecosystem: "pip"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: 0 2 * * *
      timezone: "America/New_York"
    commit-message:
      prefix: "chore(deps)"
    cooldown:
      default-days: 7
