[project]
name = "ansible-system-config"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible-core>=2.18.7",
    "ansible-dev-environment>=25.7.0",
    "ansible-lint>=25.7.0",
]
