- name: Find all files in /etc/ssh/sshd_config.d
  ansible.builtin.find:
    paths: /etc/ssh/sshd_config.d
    patterns: '*'
    file_type: file
  register: found_files

- name: Delete files in /etc/ssh/sshd_config.d that is not disable-password-auth.conf
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ found_files.files }}"
  when: "item.path.split('/')[-1] not in ['disable-password-auth.conf']"

- name: Add or modify PasswordAuthentication line in sshd config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config.d/disable-password-auth.conf
    create: true
    line: 'PasswordAuthentication no'
    state: present
    backup: false
    mode: "0644"
  notify: Restart ssh daemon
  register: disable_password_auth_conf

- name: Set PasswordAuthentication to no in sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^(#\s*)?PasswordAuthentication\s+yes'
    line: 'PasswordAuthentication no'
    mode: "0644"
  notify: Restart ssh daemon
  register: password_auth
