- name: Ensure .bashrc contains alias
  ansible.builtin.blockinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    block: "{{ lookup('ansible.builtin.template', 'aliases.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    create: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Reload bashrc
  tags:
    - alias
    - shell

- name: Stat Check .zshrc file
  ansible.builtin.stat:
    path: "/home/{{ ansible_user }}/.zshrc"
  register: alias_zshrc
  tags:
    - alias
    - shell

- name: Ensure .zshrc contains alias
  ansible.builtin.blockinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    block: "{{ lookup('ansible.builtin.template', 'aliases.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    create: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Reload zshrc
  when: alias_zshrc.stat.exists
  tags:
    - alias
    - shell