- name: Ensure .bashrc contains alias
  ansible.builtin.blockinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    block: "{{ lookup('template', 'aliases.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    create: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Reload bashrc