- name: Ensure .bashrc contains alias
  ansible.builtin.template:
    src: .bashrc.j2
    dest: "/home/{{ ansible_user }}/.bashrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Reload bashrc