- name: Install unattended-upgrades and update-notifier-common
  ansible.builtin.apt:
    pkg:
      - unattended-upgrades
      - update-notifier-common
    state: present
  tags:
    - unattended_upgrades
    - packages

- name: Copy over the 50unattended-upgrades config
  ansible.builtin.template: 
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: "0644"
  notify: Reload unattended-upgrades
  tags:
    - unattended_upgrades
    - config