- name: Transfer authorized_keys file
  ansible.builtin.template:
    src: ssh_keys.pub.j2
    dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
