galaxy_info:
  author: internal
  description: Install qemu-guest-agent on QEMU guests
  license: MIT
  min_ansible_version: '2.18'
  platforms:
    - name: Ubuntu
      versions: ['all']
dependencies: []
