# command to use:
# ansible-playbook playbooks/allow-ssh-password-auth.yml --extra-vars "$(printenv | xargs)"

- name: Allow SSH Password Authentication
  hosts: ubuntu
  become: yes

  tasks:
    - name: Set PasswordAuthentication to yes in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication yes'
      notify:
        - restart ssh

  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted
