# command to use:
# ansible-playbook playbooks/apt.yml

- name: Update Ubuntu Servers
  hosts: ubuntu
  become: yes

  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: 'yes'