# command to use:
# ansible-playbook playbooks/docker-install.yml

- name: Update Ubuntu Servers
  hosts: ubuntu
  remote_user: ubuntu
  become: yes

  tasks:
    - name: Update and upgrade all packages to the latest version
      apt:
        update_cache: true
        upgrade: dist

    - name: Check if Docker is already installed
      command: docker --version
      ignore_errors: yes
      register: is_docker_installed

    - name: Install required packages
      apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
      when: is_docker_installed is failed

    - name: Create directory for Docker's GPG key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      when: is_docker_installed is failed

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present
      when: is_docker_installed is failed

    - name: Set permissions for Docker GPG key
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: '0644'
      when: is_docker_installed is failed

    - name: Add Docker repository
      apt_repository:
        repo: >-
          deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}
          signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        filename: docker
        state: present
      when: is_docker_installed is failed

    - name: Install Docker if not already installed
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      when: is_docker_installed is failed

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes
        