# Please remember to add ssh public key to proxmox instance before using
# command to use:
# ansible-playbook playbooks/proxmox.yml

- name: Proxmox Initialization
  hosts: proxmox
  become: true
  vars:
    arch_mapping:
      x86_64: amd64
      aarch64: arm64
    ansible_become_pass: "{{ lookup('env', 'api_password') }}"
  roles:
    - proxmox