# command to use:
# ansible-playbook playbooks/qemu-guest-agent.yml --extra-vars "$(cat .env | xargs)"

- name: Install latest qemu-guest-agent
  hosts: ubuntu

  tasks:
    - name: install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
      become: true
