# command to use:
# ansible-playbook playbooks/timezone.yml --extra-vars "$(printenv | xargs)"

- name: Set timezone and configure timesyncd
  hosts: ubuntu
  become: yes
  tasks:
  - name: set timezone
    shell: timedatectl set-timezone America/Toronto

  - name: Make sure timesyncd is stopped
    systemd:
      name: systemd-timesyncd.service
      state: stopped

  - name: Copy over the timesyncd config
    template: 
      src: ../templates/timesyncd.conf
      dest: /etc/systemd/timesyncd.conf
      owner: root
      group: root
      mode: 0644
    register: copy_timesyncd_template
    
  - name: Make sure timesyncd is started
    systemd:
      name: systemd-timesyncd.service
      state: started
    when: copy_timesyncd_template is changed
