# .github/workflows/ansible-lint.yml
name: Ansible Lint
on:
  workflow_dispatch:
  pull_request:
    branches: ["main", "stable", "release/v*"]
    paths:
      - '**.yml'
      - '**.ini'
      - '**.j2'

permissions:
  pull-requests: write
  contents: write

jobs:
  lint:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        
      - name: Run ansible-lint
        uses: ansible/ansible-lint@9765b8704b2c3f4ab782815b528e0393662e1c04 # v25.7.0
        with:
          args: "--profile production"

  merge:
    needs: lint
    name: Merge PR
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.user.login == github.repository_owner }}
    steps:           
      - name: Merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash --repo ${{ github.repository }}
