# .github/workflows/ansible-lint.yml
name: Ansible Lint
on:
  workflow_dispatch:
  pull_request:
    branches: ["main", "stable", "release/v*"]
    paths:
      - '**.yml'
      - '**.ini*'

permissions:
  pull-requests: write
  contents: write

jobs:
  lint:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run ansible-lint
        uses: ansible/ansible-lint@06f616d6e86e9ce4c74393318d1cbb2d016af413 # v25.6.1

  merge:
    needs: lint
    name: Merge PR
    runs-on: ubuntu-latest
    env:
      MERGE: 'undefined'
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.user.login == github.repository_owner }}
    steps:
      - name: Check for concurrent workflow runs
        id: check_concurrent_runs
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const workflow_runs = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ansible-lint.yml',
              event: 'pull_request',
              status: 'in_progress',
            });

            const current_pr_number = context.issue.number;
            const current_run_id = context.runId;

            const other_runs_for_pr = workflow_runs.data.workflow_runs.filter(run => {
              if (run.id === current_run_id) {
                return false;
              }
              const pr_for_run = run.pull_requests.find(pr => pr.number === current_pr_number);
              return !!pr_for_run;
            });

            if (other_runs_for_pr.length > 0) {
              console.log(`Found ${other_runs_for_pr.length} other running workflows for PR #${current_pr_number}.`);
              core.exportVariable('MERGE', 'false');
            } else {
              console.log(`No other running workflows found for PR #${current_pr_number}.`);
              core.exportVariable('MERGE', 'true');
            }
              
      - name: Merge PR
        if: ${{ env.MERGE == 'true' }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: 'squash'
            })
