name: Trivy
permissions: {}

on:
  push:
    branches:
      - main

    tags:
      - '*'

  pull_request:
    branches:
      - main

  schedule:
    - cron: '30 6 * * *'
jobs:
  trivy-scan:
    if: ${{ github.repository == 'calvin-li-developer/ansible' }}
    name: Trivy Scan
    permissions:
      contents: read
      actions: read
      security-events: write
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # v0.32.0
        with:
          scan-type: repo
          ignore-unfixed: true
          format: sarif
          output: trivy-results.sarif
          severity: CRITICAL,HIGH

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@51f77329afa6477de8c49fc9c7046c15b9a4e79d # v3.29.5
        with:
          sarif_file: 'trivy-results.sarif'
